-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS `authdb`;
USE `authdb`;

-- Create the Users table matching the Entity Framework Core model
CREATE TABLE IF NOT EXISTS `Users` (
    `Id` INT AUTO_INCREMENT PRIMARY KEY,
    `Email` VARCHAR(255) NOT NULL,
    `PasswordHash` LONGTEXT NOT NULL,
    `Role` LONGTEXT NOT NULL,
    `CreatedAt` DATETIME(6) NOT NULL
);

-- Seed the initial admin user with password "Admin123!"
-- Note: The hash was generated by Microsoft.AspNetCore.Identity.PasswordHasher
INSERT INTO `Users` (`Email`, `PasswordHash`, `Role`, `CreatedAt`) 
VALUES ('admin@game.com', 'AQAAAAIAAYagAAAAEP0wQ1xIINJ+k4f16uHPEUa49l7o9n6/F6+oN9u+bC/I1c9V7p3b7rR1g0V6V+0g==', 'admin', UTC_TIMESTAMP());
